version: '3'
services:
  mongo:
    image: mongo
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=2137
      - RABBITMQ_DEFAULT_USER=user
  mysql:
    build: mysql/

  front1:
    build: front/
    depends_on:
      - "mongo"
      - "rabbit"
      - "mysql"
  front2:
    build: front/
    depends_on:
      - "mongo"
      - "rabbit"
      - "mysql"
  front3:
    build: front/
    depends_on:
      - "mongo"
      - "rabbit"
      - "mysql"
  face_recognition:
    build: face_recognition/
    depends_on:
      - "mongo"
      - "rabbit"
      - "mysql"

  nginx:
    build: nginx/
    depends_on:
      - "front1"
      - "front2"
      - "front3"
  varnish:
    build: varnish/
    ports:
      - 8080:80
    depends_on:
      - "nginx"
