version: '3'
services:
  jnp3_mongo:
    image: mongo
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=2137
      - RABBITMQ_DEFAULT_USER=user
  jnp3_mysql:
    build: mysql/
    ports:
      - 3306:3306

  flask1:
    build: flask/
    ports:
    - "5000:5000"
    depends_on:
      - "jnp3_mongo"
      - "rabbit"
      - "jnp3_mysql"
  flask2:
    build: flask/
    ports:
    - "5001:5000"
    depends_on:
      - "jnp3_mongo"
      - "rabbit"
      - "jnp3_mysql"
  flask3:
    build: flask/
    ports:
    - "5002:5000"
    depends_on:
      - "jnp3_mongo"
      - "rabbit"
      - "jnp3_mysql"
  face_recognition:
    build: face_recognition/
    ports:
      - 4999:5000
    depends_on:
      - "jnp3_mongo"
      - "rabbit"
      - "jnp3_mysql"

  jnp3_nginx:
    build: nginx/
    ports:
      - "3333:8080"
    depends_on:
      - "flask1"
      - "flask2"
      - "flask3"
  jnp3_varnish:
    build: varnish/
    ports:
      - 8080:80
    depends_on:
      - "jnp3_nginx"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
