USE baza;
CREATE TABLE images  (
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    url VARCHAR(300) NOT NULL,
    osoby VARCHAR(300) NOT NULL
    ) 
    PARTITION BY RANGE COLUMNS(id)(
    PARTITION p0 VALUES LESS THAN (5),
    PARTITION p1 VALUES LESS THAN (10),
    PARTITION p2 VALUES LESS THAN MAXVALUE
    );
